version: '3.1'

services:
  zoo:
    container_name: zoo
    image: zookeeper
    restart: on-failure
    hostname: zoo
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  rmq:
    container_name: rabbitmq
    image: rabbitmq:latest

  master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: master
    image: master:latest
    command: sh -c -u "sleep 15 && python master.py"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    links:
    - rmq
    - zoo
    depends_on:
    - rmq
    - zoo
    restart: on-failure

  slave:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: slave
    image: slave:latest
    command: sh -c -u "sleep 20 && python slave.py"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    links:
    - rmq
    - zoo
    depends_on:
    - rmq
    - zoo
    restart: on-failure

  orchestrator:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: orchestrator
    image: orchestrator:latest
    command: sh -c -u "sleep 10 && python orchestrator.py"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    depends_on:
        - zoo
    restart: on-failure    
    ports:
      - "80:80"
    

  
